# Generated by Django 5.0.1 on 2024-01-10 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 10, 15, 27, 9, 420644)),
        ),
    ]
